// <auto-generated />
using System;
using FlowFi.NotificationService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowFi.NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260619204529_AddDeletedAtAndImageUrl")]
    partial class AddDeletedAtAndImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowFi.NotificationService.Entities.DeviceSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("RecordVersion")
                        .HasColumnType("integer")
                        .HasColumnName("record_version");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_sync_states");

                    b.HasIndex("UserId", "DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_device_sync_states_user_id_device_fingerprint");

                    b.ToTable("device_sync_states", (string)null);
                });

            modelBuilder.Entity("FlowFi.NotificationService.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("NotificationType")
                        .HasDatabaseName("ix_notifications_notification_type");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FlowFi.NotificationService.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnableBudgetWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_budget_warning");

                    b.Property<bool>("EnableEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_email");

                    b.Property<bool>("EnableGoalReminder")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_goal_reminder");

                    b.Property<bool>("EnableInApp")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_in_app");

                    b.Property<bool>("EnablePush")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_push");

                    b.Property<bool>("EnableSavingStreak")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_saving_streak");

                    b.Property<bool>("EnableSystemAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_system_alert");

                    b.Property<bool>("EnableTransactionAlert")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_transaction_alert");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("text")
                        .HasColumnName("preferred_language");

                    b.Property<bool>("QuietHoursEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("quiet_hours_enabled");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_end");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("quiet_hours_start");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_settings_user_id");

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("FlowFi.NotificationService.Entities.PushDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_fingerprint");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_devices");

                    b.HasIndex("Platform")
                        .HasDatabaseName("ix_push_devices_platform");

                    b.HasIndex("Token")
                        .HasDatabaseName("ix_push_devices_token");

                    b.HasIndex("UserId", "DeviceFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_devices_user_id_device_fingerprint");

                    b.ToTable("push_devices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
