// <auto-generated />
using System;
using FlowFi.AnalyticsService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowFi.AnalyticsService.Database.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency_code");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Monthly")
                        .HasColumnName("period_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("TagName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tag_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WarningThresholdPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(80)
                        .HasColumnName("warning_threshold_percent");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("UserId", "PeriodType")
                        .HasDatabaseName("idx_budgets_user_period");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_budgets_user_status");

                    b.HasIndex("UserId", "StartDate", "EndDate")
                        .HasDatabaseName("idx_budgets_user_date");

                    b.HasIndex("UserId", "TagId", "StartDate", "EndDate")
                        .HasDatabaseName("idx_budgets_user_tag_date");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("chk_budgets_amount", "budget_amount > 0");

                            t.HasCheckConstraint("chk_budgets_date_range", "end_date >= start_date");

                            t.HasCheckConstraint("chk_budgets_period_type", "period_type IN ('Weekly', 'Monthly')");

                            t.HasCheckConstraint("chk_budgets_status", "status IN ('Active', 'Completed', 'Cancelled', 'Expired')");

                            t.HasCheckConstraint("chk_budgets_warning_threshold", "warning_threshold_percent BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.BudgetProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTimeOffset?>("ExceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exceeded_at");

                    b.Property<DateTimeOffset>("LastCalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_calculated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("RemainingAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("remaining_amount");

                    b.Property<decimal>("SpentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("spent_amount");

                    b.Property<int>("TransactionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transaction_count");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UsagePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(7,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("usage_percent");

                    b.HasKey("Id")
                        .HasName("pk_budget_progresses");

                    b.HasIndex("BudgetId")
                        .IsUnique()
                        .HasDatabaseName("idx_budget_progresses_budget_id");

                    b.ToTable("budget_progresses", null, t =>
                        {
                            t.HasCheckConstraint("chk_budget_progresses_spent_amount", "spent_amount >= 0");

                            t.HasCheckConstraint("chk_budget_progresses_transaction_count", "transaction_count >= 0");

                            t.HasCheckConstraint("chk_budget_progresses_usage_percent", "usage_percent >= 0");
                        });
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.FinancialSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AchievedGoalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("achieved_goal_count");

                    b.Property<int>("ActiveGoalCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_goal_count");

                    b.Property<decimal>("BudgetUsagePercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(7,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("budget_usage_percent");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("NetSaving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("net_saving");

                    b.Property<DateOnly>("PeriodEndDate")
                        .HasColumnType("date")
                        .HasColumnName("period_end_date");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date")
                        .HasColumnName("period_start_date");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_type");

                    b.Property<decimal>("TotalBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_budget");

                    b.Property<decimal>("TotalExpense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_expense");

                    b.Property<decimal>("TotalIncome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_income");

                    b.Property<int>("TransactionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("transaction_count");

                    b.Property<decimal>("UsedBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("used_budget");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_financial_summaries");

                    b.HasIndex("UserId", "Year", "Month")
                        .HasDatabaseName("idx_financial_summaries_user_year_month");

                    b.HasIndex("UserId", "Year", "WeekNumber")
                        .HasDatabaseName("idx_financial_summaries_user_year_week");

                    b.HasIndex("UserId", "PeriodType", "PeriodStartDate", "PeriodEndDate")
                        .IsUnique()
                        .HasDatabaseName("uq_financial_summaries_user_period");

                    b.ToTable("financial_summaries", null, t =>
                        {
                            t.HasCheckConstraint("chk_financial_summaries_amounts", "total_income >= 0 AND total_expense >= 0 AND total_budget >= 0 AND used_budget >= 0 AND budget_usage_percent >= 0");

                            t.HasCheckConstraint("chk_financial_summaries_counts", "transaction_count >= 0 AND active_goal_count >= 0 AND achieved_goal_count >= 0");

                            t.HasCheckConstraint("chk_financial_summaries_date_range", "period_end_date >= period_start_date");

                            t.HasCheckConstraint("chk_financial_summaries_month", "month IS NULL OR month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("chk_financial_summaries_period_type", "period_type IN ('Weekly', 'Monthly')");

                            t.HasCheckConstraint("chk_financial_summaries_week_number", "week_number IS NULL OR week_number BETWEEN 1 AND 53");

                            t.HasCheckConstraint("chk_financial_summaries_weekly_monthly", "((period_type = 'Weekly' AND week_number IS NOT NULL AND month IS NULL) OR (period_type = 'Monthly' AND month IS NOT NULL AND week_number IS NULL))");

                            t.HasCheckConstraint("chk_financial_summaries_year", "year >= 2000");
                        });
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.GoalContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("ContributionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contribution_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("SourceReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_reference_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_goal_contributions");

                    b.HasIndex("GoalId", "ContributionDate")
                        .HasDatabaseName("idx_goal_contributions_goal_date");

                    b.ToTable("goal_contributions", null, t =>
                        {
                            t.HasCheckConstraint("chk_goal_contributions_amount", "amount > 0");

                            t.HasCheckConstraint("chk_goal_contributions_source_type", "source_type IN ('Manual', 'AutoAllocation', 'RoundUp', 'FromTransaction')");
                        });
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.SavingGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_amount");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Medium")
                        .HasColumnName("priority_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saving_goals");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_saving_goals_user_status");

                    b.HasIndex("UserId", "TargetDate")
                        .HasDatabaseName("idx_saving_goals_user_target_date");

                    b.ToTable("saving_goals", null, t =>
                        {
                            t.HasCheckConstraint("chk_saving_goals_current_amount", "current_amount >= 0");

                            t.HasCheckConstraint("chk_saving_goals_priority_level", "priority_level IN ('Low', 'Medium', 'High')");

                            t.HasCheckConstraint("chk_saving_goals_status", "status IN ('Active', 'Achieved', 'Cancelled')");

                            t.HasCheckConstraint("chk_saving_goals_target_amount", "target_amount > 0");
                        });
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.BudgetProgress", b =>
                {
                    b.HasOne("FlowFi.AnalyticsService.Entities.Budget", "Budget")
                        .WithOne("Progress")
                        .HasForeignKey("FlowFi.AnalyticsService.Entities.BudgetProgress", "BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_progresses_budget");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.GoalContribution", b =>
                {
                    b.HasOne("FlowFi.AnalyticsService.Entities.SavingGoal", "Goal")
                        .WithMany("Contributions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goal_contributions_goal");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.Budget", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("FlowFi.AnalyticsService.Entities.SavingGoal", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
